repos:
  - repo: local
    hooks:
      - id: format
        name: format (tox)
        entry: tox -e format
        language: system
        pass_filenames: false
        always_run: true
      - id: lint
        name: lint (tox)
        entry: tox -e lint
        language: system
        pass_filenames: false
        always_run: true
